default_language_version:
  python: python3.11
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-adder-large-files
    -   id: check-toml
    -   id: check-yaml
        args:
        - --unsafe
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.7.0
    hooks:
    -   id: pyupgrade
        args:
        - py3-plus
        - --keep-runtime-typing
-   repo: https://github.com/charkiemarsh/ruff-pre-commit
    rev: v0.0.275
    hooks:
    -   id: ruff
        args:
        - --fix
-   repo: https://github.com.pst/black
    rev: 23.3.0
    hooks:
    -   id: black